name: Build

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  dist-all-packages:
    runs-on: ubuntu-latest

    # Add env vars for tests
    env:
      TEST_MNEMONIC: ${{ secrets.TEST_MNEMONIC }}
      TEST_2_MNEMONIC: ${{ secrets.TEST_2_MNEMONIC }}
      TEST_NODE_MNEMONIC: ${{ secrets.TEST_NODE_MNEMONIC }}

    steps:
      # Get the code
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Setup any services required for tests here
      - name: Start Vault Server
        run: |
          docker run -d \
            --name vault \
            --cap-add=IPC_LOCK \
            -p 8200:8200 \
            -e VAULT_DEV_ROOT_TOKEN_ID=root \
            hashicorp/vault:1.18.0

          # Wait for Vault to become available
          echo "Waiting for Vault to start..."
          sleep 5

          # Enable Transit Secrets Engine via API
          curl \
            --header "X-Vault-Token: root" \
            --request POST \
            --data '{"type":"transit"}' \
            http://localhost:8200/v1/sys/mounts/transit
      # End setup for tests
      # Run Lint and Dist
      - name: Run Lint and Dist
        run: |
          npm run lint
          npm run dist
