name: Build, Lint, Test, Docs Next

on:
  pull_request:
    branches-ignore:
      - main

jobs:
  dist:
    runs-on: ubuntu-latest

    env:
      TEST_MNEMONIC: ${{ secrets.TEST_MNEMONIC }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Start Hashicorp Vault
        run: |
          docker run -d --name twin-entity-storage-vault --cap-add=IPC_LOCK -e 'VAULT_DEV_ROOT_TOKEN_ID=root' -p 8200:8200 hashicorp/vault

      - name: Wait for Vault to be ready
        run: |
          for i in {1..10}; do
            STATUS=$(curl -s -o /dev/null -w '%{http_code}' http://127.0.0.1:8200/v1/sys/health)
            if [ "$STATUS" -eq 200 ]; then
              echo "Vault is ready"
              break
            fi
            echo "Waiting for Vault to be ready..."
            sleep 3
          done

      - name: Enable Transit Secrets Engine inside Vault container
        run: |
          docker exec -e VAULT_ADDR='http://127.0.0.1:8200' -e VAULT_TOKEN='root' twin-entity-storage-vault vault secrets enable transit


      - name: Restore root node_modules from cache
        id: node-cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Run Lint and Dist
        run: |
          npm run lint
          npm run dist
