name: Publish Next All Packages

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    if: github.ref != 'refs/heads/main'

    services:
      vault:
        image: hashicorp/vault:1.18.0
        ports:
          - 8200:8200
        env:
          VAULT_DEV_ROOT_TOKEN_ID: root
        options: >-
          --cap-add=IPC_LOCK

    strategy:
      max-parallel: 1
      matrix:
        package:
          [
            'packages/vault-models',
            'packages/vault-connector-entity-storage',
            'packages/vault-connector-hashicorp'
          ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: next

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Set Vault environment variables
        run: |
          echo "VAULT_ADDR=http://localhost:8200" >> $GITHUB_ENV
          echo "VAULT_TOKEN=root" >> $GITHUB_ENV

      - name: Enable Transit Secrets Engine via API
        run: |
          curl \
            --header "X-Vault-Token: $VAULT_TOKEN" \
            --request POST \
            --data '{"type":"transit"}' \
            $VAULT_ADDR/v1/sys/mounts/transit

      - name: Remove Mono-Repo Node Modules
        run: |
          rm package.json
          rm package-lock.json

      - name: Check package version contains -next
        run: |
          cd ${{ matrix.package }}
          PACKAGE_VERSION=$(cat package.json | jq '.version' | tr -d '"')
          echo Package Version $PACKAGE_VERSION
          if [[ $PACKAGE_VERSION != *"-next"* ]]; then
            echo "Error: package version does not contain -next"
            exit 1
          fi

      - name: Run Dist
        run: |
          cd ${{ matrix.package }}
          npm install
          npm run dist

      - name: Cleanup package properties
        run: |
          cd ${{ matrix.package }}
          npm pkg delete scripts
          npm pkg delete devDependencies

      - name: Publish
        run: |
          cd ${{ matrix.package }}
          npm publish --provenance --access public --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
